name: CI
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri

      - run: npm ci
      - run: npm run lint
      - run: npm run knip
      - run: npm run tauri build -- --no-bundle
